= 颜色和像素图
:toc:
:toc-title: 目录
:numbered:

== 用颜色绘制彩虹
到目前为止，我们所有的绘画操作都是使用黑白完成的。 现在，我们终于能看到如何使用颜色进行绘制。

=== 颜色映射
最初，并没有足够多的颜色。屏幕控制器只能同时支持有限数量的颜色（最初是2种，然后是4种，16种和256种）。
因此，应用程序不能只要求绘制“浅紫红色”颜色，并期望该颜色可用。
每个应用程序分配了所需的颜色，并且在所有颜色条目（4、16、256种颜色）都被使用时，下一次颜色分配将失败。

于是就引入了 “颜色映射” 的概念。颜色映射是一个表，其大小与给定屏幕控制器能同时显示的颜色数量相同。
每个条目包含不同颜色的RGB(红色、绿色和蓝色)值(可以使用红色、绿色和蓝色的组合绘制所有颜色)。
当应用程序想要在屏幕上绘图时，它不会指定使用哪种颜色。相反，它指定在此绘图期间使用颜色映射的哪个颜色项。
更改此颜色映射项中的值，绘图将使用不同的颜色。

为了能够使用程序员想用的颜色进行绘制，我们提供了颜色映射分配功能。
您可以要求为具有一组RGB值的颜色分配条目。 如果已经存在，则将在表中获取其索引。
如果不存在，并且表未满，则将分配一个新单元格以包含给定的RGB值，并返回其索引。如果表已满，则该过程将失败。
然后，您可以要求获得一个颜色映射表项，该表项的颜色与您要的颜色最接近。
这意味着屏幕上的实际绘图将使用与您想要的颜色相似但不相同的颜色进行。

在当今X服务器运行着支持1600万种颜色的更现代的屏幕上，此限制看起来有些愚蠢，但请记住，仍然有一些旧计算机配备了旧显卡。
使用颜色图，对这些屏幕的支持对您来说是透明的。在支持1600万种颜色的显示器上，任何颜色输入分配请求都会成功。
在支持有限数量的颜色的显示器上，某些颜色分配请求将返回相似的颜色。
这看起来不太好，但是您的应用程序仍然可以运行。

=== 分配和释放颜色映射
在你使用XCB进行绘图的时候，你可以选择使用你显示出来窗口的屏幕提供的标准颜色映射，或者你也可以重新分配分配一个新的颜色映射并应用到你的窗口上面。
在后一种情况下，每次将鼠标移到窗口上时，屏幕颜色映射都会被窗口的颜色映射替换，您将看到屏幕上所有其他窗口的颜色都变得非常奇怪。 实际上，这是使用“ -install”命令行选项的X应用程序所获得的效果。

在XCB中，颜色映射是（通常在X中）一个ID：
[source,c]
....
typedef uint32_t xcb_colormap_t;
....

为了获取屏幕默认的颜色映射，你仅仅需要检索 `xcb_screen_t` 结构体的 `default_colormap` 字段：
[source,c]
....
xcb_colormap_t colormap = screen->default_colormap;
....

这将返回默认情况下在第一个屏幕上使用的颜色映射（同样，请记住X服务器可能支持几个不同的屏幕，每个屏幕可能都有自己的资源）。

另一种选择是分配新的颜色映射，其工作方式如下。 我们首先要求X服务器使用以下功能为我们的颜色映射提供ID：
[source,c]
....
xcb_colormap_t
xcb_generate_id (xcb_connection_t *connection);
....
Then, we create the color map with
[source,c]
....
xcb_void_cookie_t
xcb_create_colormap (xcb_connection_t *connection,
                        uint8_t           alloc,   /* Colormap entries to be allocated (AllocNone or AllocAll) */
                        xcb_colormap_t    mid,     /* Id of the color map */
                        xcb_window_t      window,  /* Window on whose screen the colormap will be created */
                        xcb_visualid_t    visual ); /* Id of the visual supported by the screen */
....
下面有一个创建新的颜色映射示例：
[source,c]
....
#include <xcb/xcb.h>

int
main ()
{
    /* open the connection to the X server and get the first screen */
    xcb_connection_t  *connection  = xcb_connect (NULL, NULL);
    xcb_screen_t      *screen      = xcb_setup_roots_iterator (xcb_get_setup (connection)).data;

    /* ...assume we create a window here... */

    xcb_colormap_t colormapId = xcb_generate_id (connection);
    xcb_create_colormap (connection,
                            XCB_COLORMAP_ALLOC_NONE,
                            colormapId,
                            window,
                            screen->root_visual );

    return 0;
}
....

NOTE: window参数仅用于允许X服务器为给定屏幕创建颜色图。 然后，我们可以将此颜色映射用于在同一屏幕上绘制的任何窗口。

为了释放颜色映射,用下面这个函数就足够了：
[source,c]
....
xcb_void_cookie_t
xcb_free_colormap (xcb_connection_t  *connection,
                    xcb_colormap_t     colormapId );
....

Xlib/XCB比较:

- XCreateColormap () =>
[source,c]
....
xcb_generate_id ()
xcb_create_colormap () 
....

- XFreeColormap () =>
[source,c]
....
xcb_free_colormap () 
....

=== 分配和释放颜色条目
一旦获取到了颜色映射，就可以开始分配颜色。与颜色有关的信息以以下结构存储：
[source,c]
....
typedef struct {
    uint8_t  response_type;
    uint8_t  pad0;
    uint16_t sequence;
    uint32_t length;
    uint16_t red;          /* The red component   */
    uint16_t green;        /* The green component */
    uint16_t blue;         /* The blue component  */
    uint8_t  pad1[2];
    uint32_t pixel;        /* The entry in the color map, supplied by the X server */
} xcb_alloc_color_reply_t;
....

XCB提供了以下两个函数来填充它：
[source,c]
....
xcb_alloc_color_cookie_t
xcb_alloc_color (xcb_connection_t  *connection,
                    xcb_colormap_t     colormapId,
                    uint16_t           red,
                    uint16_t           green,
                    uint16_t           blue );

xcb_alloc_color_reply_t *
xcb_alloc_color_reply (xcb_connection_t          *connection,
                        xcb_alloc_color_cookie_t   cookie,
                        xcb_generic_error_t      **e );
....

函数 `xcb_alloc_color()` 将3个RGB分量作为参数（红色，绿色和蓝色）。这是使用这些函数的示例：
[source,c]
....
#include <malloc.h>

#include <xcb/xcb.h>

int
main ()
{
    /* open the connection to the X server and get the first screen */
    xcb_connection_t  *connection = xcb_connect (NULL, NULL);
    xcb_screen_t      *screen     = xcb_setup_roots_iterator (xcb_get_setup (connection)).data;

    /* ...assume window created here... */

    xcb_colormap_t colormapId = xcb_generate_id (connection);
    xcb_create_colormap (connection, XCB_COLORMAP_ALLOC_NONE, colormapId, window, screen->root_visual);

    xcb_alloc_color_reply_t *reply = xcb_alloc_color_reply (connection,
                                                            xcb_alloc_color (connection,
                                                                                colormapId,
                                                                                65535,
                                                                                0,
                                                                                0),
                                                            NULL );

    if (!reply) {
        return 0;
    }

    /* ...do something with reply->pixel... */

    free (reply);

    return 0;
}
....

TODO: 谈谈关于颜色释放。

== X位图和像素图
许多应用程序会做的一件事就是显示图像。在X世界中，这是使用位图和像素图完成的。
在为我们的应用程序设置图标时，我们已经看到了它们的一些用法。
让我们进一步研究它们，看看如何在窗口内沿着到目前为止我们看到的简单图元和文本绘制这些图像。

在进一步研究之前要注意的一件事是，XCB和Xlib都没有提供处理常用图像格式（例如gif，png，jpeg或tiff）的方法。
为了在X中显示，我们必须使用更高级别的图形库将这些格式转换为X位图或X像素图。

=== 什么是X位图和像素图?
X位图是以特定于X窗口系统的格式存储的两色图像。 当存储在文件中时，位图数据看起来像C源文件。 它包含用于标识位图的宽度和高度的成员，还包含一个用来存储位图位值的数组（数组的大小为（width + 7）/ 8 * height），位和字节的顺序为LSB），以及一个可选的热点位置，这会在有关鼠标光标的部分进行说明。

X像素图是一种用于将图像存储在X服务器的内存中的格式。此格式可以存储黑白图像（例如x位图）以及彩色图像。这是X协议支持的唯一图像格式，任何要在屏幕上绘制的图像都应首先转换为该格式。

可以将X像素图视为没有出现在屏幕上的窗口，因为在窗口上运行的许多图形操作也将在像素图上运行。 实际上，XCB中X像素图的类型是一个类似于窗口的ID：
[source,c]
....
typedef uint32_t xcb_pixmap_t;
....
在窗口或像素图上执行的操作是一样的，这些操作采用xcb_drawable_t参数：
[source,c]
....
typedef uint32_t xcb_drawable_t;
....
在Xlib中，Drawable，Pixmap或Window之间没有特定的区别---都是32位长的整数---XCB将所有这些不同的ID包装在结构中以提供某种类型安全性。

=== 创建像素图
有时我们想创建一个未初始化的像素图，以便后面可以使用它。 这对于图像绘制程序很有用（创建一个新的空白画布时会创建一个新的像素图，要绘制的内容可以存储在上面）。 在读取各种图像格式时，它也很有用：我们将图像数据加载到内存中，在服务器上创建一个像素图，然后将解码的图像数据绘制到该像素图上。

要创建一个新的像素图，我们首先要求X服务器使用以下函数为我们的像素图提供一个ID：
[source,c]
....
xcb_pixmap_t
xcb_generate_id (xcb_connection_t *connection);
....
然后，XCB提供以下函数来创建新的像素图：
[source,c]
....
xcb_void_cookie_t
xcb_create_pixmap (xcb_connection_t *connection,
                    uint8_t           depth,     /* depth of the screen */
                    xcb_pixmap_t      pixmapId,  /* id of the pixmap */
                    xcb_drawable_t    drawable,
                    uint16_t          width,     /* pixel width of the window */
                    uint16_t          height );  /* pixel height of the window */
....
TODO: 解释drawable参数, 并给出一个例子 (就像xpoints.c那样)

=== 在窗口上绘制像素图
一旦获得了像素图的句柄，就可以使用以下函数在某个窗口上绘制它：
[source,c]
....
xcb_void_cookie_t
xcb_copy_area (xcb_connection_t *connection,
                xcb_drawable_t    src_drawable,  /* drawable we want to paste */
                xcb_drawable_t    dst_drawable,  /* drawable on which we copy the previous Drawable */
                xcb_gcontext_t    gc,            
                int16_t           src_x,         /* top left x coordinate of the region we want to copy */
                int16_t           src_y,         /* top left y coordinate of the region we want to copy */
                int16_t           dst_x,         /* top left x coordinate of the region where we want to copy */
                int16_t           dst_y,         /* top left y coordinate of the region where we want to copy */
                uint16_t          width,         /* pixel width of the region we want to copy */
                uint16_t          height );      /* pixel height of the region we want to copy */
....

如您所见，我们可以复制整个像素图以及像素图的给定矩形区域。 这对于优化绘图速度很有用：我们只需要复制在像素图中被修改的那部分内容即可。

需要注意的一个重要事项是：可以在同一屏幕上创建具有不同深度的像素图。当我们执行复制操作（在窗口上的像素图等）时，我们应确保源和目标的深度相同。 
如果深度不同，则操作将失败。 例外是如果我们使用 `xcb_copy_plane()` 复制源像素图的特定的位平面。
在这种情况下，我们可以将特定的平面复制到目标窗口（实际上，在复制的每个像素的颜色中设置特定的位）。 
这可用于在窗口中生成奇怪的图形效果，但这超出了本教程的范围。

=== 释放像素图
最后，使用完给定的像素图后，应释放它，以便释放X服务器的资源。 使用以下功能可以完成此操作：
[source,c]
....
xcb_void_cookie_t
xcb_free_pixmap (xcb_connection_t *connection,
                    xcb_pixmap_t pixmap );
....

TODO: 给定一个例子，或者xpoints.c的链接。

Links: link:tutorial.adoc[tutorial]

Last edited Mon 02 Nov 2009 02:55:18 PM UTC