= 窗口上下文与操作
:toc:
:numbered:

== 与窗口管理器交互
在了解了如何创建窗口并在其上绘制之后，我们再深入一步，看看我们的窗口如何与其环境（全屏和其他窗口）交互。
首先，我们的应用程序需要与窗口管理器进行交互。窗口管理器负责装饰绘制的窗口（即添加框架，图标化按钮，系统菜单，标题栏等），以及处理窗口被图标化时显示的图标。 它还处理屏幕上的窗口顺序以及其他管理任务。 我们需要给它各种提示，以表明我们希望它如何处理应用程序的窗口。

=== 窗口属性
传递给窗口管理器的许多参数是通过称为“属性”的数据来传递过去的。 X服务器将这些属性附加到不同的窗口，并以一种特定的格式存储。这种格式使得属性数据可以从使用使用不同体系结构的不同机器上读取到（请记住，X客户端程序可以在远程机器上运行）。

属性和其类型(字符串，整数等)是ID。它们的类型是 `xcb_atom_t` ：
[source,c]
....
typedef uint32_t xcb_atom_t;
....

要更改窗口的属性，我们可以使用以下函数：
[source,c]
....
xcb_void_cookie_t xcb_change_property (xcb_connection_t *c,       /* Connection to the X server */
                                        uint8_t          mode,     /* Property mode */
                                        xcb_window_t     window,   /* Window */
                                        xcb_atom_t       property, /* Property to change */
                                        xcb_atom_t       type,     /* Type of the property */
                                        uint8_t          format,   /* Format of the property (8, 16, 32) */
                                        uint32_t         data_len, /* Length of the data parameter */
                                        const void      *data);    /* Data */
....

`mode` 参数可以是下面值(该值是定义在 xproto.h 头文件中的 xcb_prop_mode_t 枚举类型)中的一个：

....
XCB_PROP_MODE_REPLACE
XCB_PROP_MODE_PREPEND
XCB_PROP_MODE_APPEND
....

=== 设置窗口名称和图标名称
我们要做的第一件事是为我们的窗口设置名称。 这是使用 `xcb_change_property()` 函数完成的。 窗口管理器将会把此名称作为窗口的标题（在标题栏中），在任务列表等。用于设置窗口名称的属性atom为 `XCB_ATOM_WM_NAME` （对于图标化窗口，则为XCB_ATOM_WM_ICON_NAME），其类型为XCB_ATOM_STRING。 这是使用的示例：
[source,c]
....
#include <string.h>

#include <xcb/xcb.h>
#include <xcb/xcb_atom.h>

int
main ()
{
    /* open the connection to the X server */
    xcb_connection_t *connection = xcb_connect (NULL, NULL);


    /* get the first screen */
    xcb_screen_t *screen = xcb_setup_roots_iterator (xcb_get_setup (connection)).data;


    /* create the window */

    xcb_window_t window = xcb_generate_id (connection);
    xcb_create_window (connection, 
                        0,                             /* depth               */
                        window,
                        screen->root,                  /* parent window       */
                        0, 0,                          /* x, y                */
                        250, 150,                      /* width, height       */
                        10,                            /* border_width        */
                        XCB_WINDOW_CLASS_INPUT_OUTPUT, /* class               */
                        screen->root_visual,           /* visual              */
                        0, NULL );                     /* masks, not used     */


    /* set the title of the window */

    char *title = "Hello World !";
    xcb_change_property (connection,
                            XCB_PROP_MODE_REPLACE,
                            window,
                            XCB_ATOM_WM_NAME,
                            XCB_ATOM_STRING,
                            8,
                            strlen (title),
                            title );


    /* set the title of the window icon */

    char *iconTitle = "Hello World ! (iconified)";
    xcb_change_property (connection,
                            XCB_PROP_MODE_REPLACE,
                            window,
                            XCB_ATOM_WM_ICON_NAME,
                            XCB_ATOM_STRING,
                            8,
                            strlen(iconTitle),
                            iconTitle);


    /* map the window on the screen */

    xcb_map_window (connection, window);
    xcb_flush (connection);


    /* event loop (in this case, no events to handle) */ 
    while (1) {}

    return 0;
}
....

NOTE: 使用了atoms就需要我们的程序编译和链接xcb_atom。因此我们需要这样操作：

[source,bash]
....
gcc prog.c -o prog `pkg-config --cflags --libs xcb-atom`
....

以便程序编译正常。

== 简单的窗口操作
我们能对窗口做的另一件事是在屏幕上对窗口进行操作（调整它们的大小，移动它们，升高或降低它们，图标化等等）。
XCB为此提供了一些窗口操作功能。

=== 窗口映射与窗口取消映射
我们可以在窗口上执行的第一对操作是对其进行映射或取消映射。映射窗口会使窗口显示在屏幕上，就像我们在简单的窗口程序示例中看到的那样。
取消映射会导致将其从屏幕上删除（尽管作为逻辑实体的窗口仍然存在）。这具有使窗口隐藏（未映射）并再次显示（映射）的效果。
例如，如果我们的程序中有一个对话框窗口，而不是每次用户要求打开它时都创建一个对话框窗口，我们可以以非映射模式创建一次该窗口，并且当用户要求打开它时， 我们只是将窗口映射到屏幕上。
当用户单击“确定”或“取消”按钮时，我们只需取消。

要映射窗口，我们可以使用下面的这个函数：

[source,c]
....
xcb_void_cookie_t xcb_map_window (xcb_connection_t *c,
                                    xcb_window_t      window );
....
上面的例子就是一个很简单的使用示例。映射操作会导致一个暴露事件发送到我们的应用程序上，除非这个窗口完全被其他的窗口覆盖住了。

取消窗口映射也是非常简单的。你可以使用下面的这个函数：

[source,c]
....
xcb_void_cookie_t xcb_unmap_window (xcb_connection_t *c,
                                    xcb_window_t      window );
....

这个函数的使用方式跟 `xcb_map_window()` 是一样的。

=== 配置窗口
As we have seen when we have created our first window, in the X Events subsection, we can set some attributes for the window (that is, the position, the size, the events the window will receive, etc). If we want to modify them, but the window is already created, we can change them by using the following function:

[source,c]
....
xcb_void_cookie_t xcb_configure_window (xcb_connection_t *c,            /* The connection to the X server*/
                                        xcb_window_t      window,       /* The window to configure */
                                        uint16_t          value_mask,   /* The mask */
                                        const uint32_t   *value_list);  /* The values to set */
....

We set the value_mask to one or several mask values that are in the xcb_config_window_t enumeration in the xproto.h header:
[source,c]
....
XCB_CONFIG_WINDOW_X             // new x coordinate of the window's top left corner
XCB_CONFIG_WINDOW_Y             // new y coordinate of the window's top left corner
XCB_CONFIG_WINDOW_WIDTH         // new width of the window
XCB_CONFIG_WINDOW_HEIGHT        // new height of the window
XCB_CONFIG_WINDOW_BORDER_WIDTH  // new width of the border of the window
XCB_CONFIG_WINDOW_SIBLING
XCB_CONFIG_WINDOW_STACK_MODE    // the new stacking order
....

We then give to value_mask the new value. We now describe how to use xcb_configure_window_t in some useful situations.

=== 在屏幕上移动窗口
An operation we might want to do with windows is to move them to a different location. This can be done like this:
[source,c]
....
const static uint32_t values[] = { 10, 20 };

/* Move the window to coordinates x = 10 and y = 20 */
xcb_configure_window (connection, window, XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y, values);
....

Note that when the window is moved, it might get partially exposed or partially hidden by other windows, and thus we might get Expose events due to this operation.

=== 调整窗口大小
Yet another operation we can do is to change the size of a window. This is done using the following code:
[source,c]
....
const static uint32_t values[] = { 200, 300 };

/* Resize the window to width = 200 and height = 300 */
xcb_configure_window (connection, window, XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT, values);
....

We can also combine the move and resize operations using one single call to xcb_configure_window_t:
[source,c]
....
const static uint32_t values[] = { 10, 20, 200, 300 };

/* Move the window to coordinates x = 10 and y = 20 */
/* and resize the window to width = 200 and height = 300 */
xcb_configure_window (connection, window, XCB_CONFIG_WINDOW_X | XCB_CONFIG_WINDOW_Y | XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT, values);
....

=== 更改窗口堆叠顺序：升高和降低
Until now, we changed properties of a single window. We'll see that there are properties that relate to the window and other windows. One of them is the stacking order. That is, the order in which the windows are layered on top of each other. The front-most window is said to be on the top of the stack, while the back-most window is at the bottom of the stack. Here is how to manipulate our windows stack order:
[source,c]
....
const static uint32_t values[] = { XCB_STACK_MODE_ABOVE };

/* Move the window on the top of the stack */
xcb_configure_window (connection, window, XCB_CONFIG_WINDOW_STACK_MODE, values);

const static uint32_t values[] = { XCB_STACK_MODE_BELOW };

/* Move the window on the bottom of the stack */
xcb_configure_window (connection, window, XCB_CONFIG_WINDOW_STACK_MODE, values);
....
=== 获取关于窗口的信息
Just like we can set various attributes of our windows, we can also ask the X server supply the current values of these attributes. For example, we can check where a window is located on the screen, what is its current size, whether it is mapped or not, etc. The structure that contains some of this information is:
[source,c]
....
typedef struct {
    uint8_t      response_type;
    uint8_t      depth;         /* depth of the window */
    uint16_t     sequence;
    uint32_t     length;
    xcb_window_t root;          /* Id of the root window *>
    int16_t      x;             /* X coordinate of the window's location */
    int16_t      y;             /* Y coordinate of the window's location */
    uint16_t     width;         /* Width of the window */
    uint16_t     height;        /* Height of the window */
    uint16_t     border_width;  /* Width of the window's border */
} xcb_get_geometry_reply_t;
....

Two functions fill this structure:
[source,c]
....
xcb_get_geometry_cookie_t xcb_get_geometry (xcb_connection_t *connection,
                                            xcb_drawable_t    drawable );

xcb_get_geometry_reply_t *xcb_get_geometry_reply (xcb_connection_t          *connection,
                                                    xcb_get_geometry_cookie_t  cookie,
                                                    xcb_generic_error_t      **error);
....

You use them as follows:
[source,c]
....
xcb_get_geometry_cookie_t  geomCookie = xcb_get_geometry (connection, window);  // window is a xcb_drawable_t
xcb_get_geometry_reply_t  *geom       = xcb_get_geometry_reply (connection, geomCookie, NULL);
/* ...do stuff with geom... */
free (geom);
....

One problem is that the returned location of the window is relative to its parent window. This makes these coordinates rather useless for any window manipulation functions, like moving it on the screen. In order to overcome this problem, we need to take a two-step operation. First, we find out the Id of the parent window of our window. We then translate the above relative coordinates to the screen coordinates.

To get the Id of the parent window, we need this structure:
[source,c]
....
typedef struct {
    uint8_t      response_type;
    uint8_t      pad0;
    uint16_t     sequence;
    uint32_t     length;
    xcb_window_t root;
    xcb_window_t parent;       /* Id of the parent window */
    uint16_t     children_len;
    uint8_t      pad1[14];
} xcb_query_tree_reply_t;
....

To fill this structure, we use these two functions:
[source,c]
....
xcb_query_tree_cookie_t xcb_query_tree       (xcb_connection_t        *connection,
                                                xcb_window_t             window );

xcb_query_tree_reply_t *xcb_query_tree_reply (xcb_connection_t        *connection,
                                                xcb_query_tree_cookie_t  cookie,
                                                xcb_generic_error_t    **error );
....

The translated coordinates will be found in this structure:
[source,c]
....
typedef struct {
    uint8_t      response_type;
    uint8_t      same_screen;
    uint16_t     sequence;
    uint32_t     length;
    xcb_window_t child;
    uint16_t     dst_x;        /* Translated x coordinate */
    uint16_t     dst_y;        /* Translated y coordinate */
} xcb_translate_coordinates_reply_t;
....

As usual, we need two functions to fill this structure:
[source,c]
....
xcb_translate_coordinates_cookie_t xcb_translate_coordinates (xcb_connection_t     *c,
                                                                xcb_window_t          src_window,
                                                                xcb_window_t          dst_window,
                                                                int16_t               src_x,
                                                                int16_t               src_y );

xcb_translate_coordinates_reply_t *xcb_translate_coordinates_reply (xcb_connection_t                    *c,
                                                                    xcb_translate_coordinates_cookie_t   cookie,
                                                                    xcb_generic_error_t                **e );
....

We use them as follows:
[source,c]
....
/* assume connection and window */

xcb_get_geometry_reply_t *geom = xcb_get_geometry_reply (connection,
                                                            xcb_get_geometry (connection, window), 
                                                            NULL );
if (!geom) {
    return 0;
}

xcb_query_tree_reply_t *tree = xcb_query_tree_reply (connection,
                                                        xcb_query_tree (connection, window),
                                                        NULL );
if (!tree) {
    return 0;
}

xcb_translate_coordinates_cookie_t translateCookie = xcb_translate_coordinates (connection,
                                                                                window,
                                                                                tree->parent,
                                                                                geom->x, geom->y );

xcb_translate_coordinates_reply_t *trans = xcb_translate_coordinates_reply (connection, 
                                                                            translateCookie,
                                                                            NULL );
if (!trans) {
    return 0;
}

/* the translated coordinates are in trans->dst_x and trans->dst_y */

free (trans);
free (tree);
free (geom);
....
The work is a bit verbose, but XCB is a quite low-level library.

TODO: the utilization of these functions should be a prog, which displays the coordinates of the window.

There is another structure that gives informations about our window:
[source,c]
....
typedef struct {
    uint8_t        response_type;
    uint8_t        backing_store;
    uint16_t       sequence;
    uint32_t       length;
    xcb_visualid_t visual;                /* Visual of the window */
    uint16_t       _class;
    uint8_t        bit_gravity;
    uint8_t        win_gravity;
    uint32_t       backing_planes;
    uint32_t       backing_pixel;
    uint8_t        save_under;
    uint8_t        map_is_installed;
    uint8_t        map_state;             /* Map state of the window */
    uint8_t        override_redirect;
    xcb_colormap_t colormap;              /* Colormap of the window */
    uint32_t       all_event_masks;
    uint32_t       your_event_mask;
    uint16_t       do_not_propagate_mask;
} xcb_get_window_attributes_reply_t;

XCB supplies these two functions to fill it:

xcb_get_window_attributes_cookie_t xcb_get_window_attributes (xcb_connection_t *connection,
                                                                xcb_window_t      window );

xcb_get_window_attributes_reply_t *xcb_get_window_attributes_reply (xcb_connection_t                   *connection,
                                                                    xcb_get_window_attributes_cookie_t  cookie,
                                                                    xcb_generic_error_t               **e );
....

You use them as follows:
[source,c]
....
/* assume connection and window */

xcb_get_window_attributes_cookie_t  attributesCookie = xcb_get_window_attributes (connection, window);
xcb_get_window_attributes_reply_t  *attributes       = xcb_get_window_attributes_reply (connection,
                                                                                        attributesCookie,
                                                                                        NULL );

if (!attributes) {
    return 0;
}

/* ...do something with attributes... */

free (attributes);
....

As for geom, attr has to be freed.

Links: link:tutorial.adoc[tutorial]

Last edited Thu 21 Nov 2013 11:53:45 AM UTC