= 事件
:toc:
:toc-title: 目录
:numbered:

== X 事件
在X程序中，一切都是由事件驱动的。
屏幕上的事件绘制有时是作为对事件（Expose事件）的响应而完成的。
如果程序窗口的一部分被隐藏（例如，该窗口在其他窗口上方升高），则X服务器将发送“ expose”事件，以使程序知道应重新绘制该窗口的那部分。 
用户输入（按键，鼠标移动等）也作为一组事件接收。

=== 使用事件掩码注册事件类型
在创建窗口的过程中，应该给它提供它希望接收的事件。 
因此，您可以注册各种鼠标（也称为指针）事件，键盘事件，暴露事件等。
这样做是为了优化服务器到客户端的连接（为什么要向程序（甚至可能正在地球的另一端运行）发送它不感兴趣的事件？）

在XCB中，您可以使用 `xcb_create_window（）` 函数中的 `"valuemask"` 和 `"valuelist"` 数据来注册事件。
下面就是我们在创建窗口时进行注册Expose事件的方法：

[source,c]
....
mask = XCB_CW_EVENT_MASK;
valwin[0] = XCB_EVENT_MASK_EXPOSURE;
win = xcb_generate_id (connection);
xcb_create_window (connection, depth, window, root->root,
                    0, 0, 150, 150, 10,
                    XCB_WINDOW_CLASS_INPUT_OUTPUT, root->root_visual,
                    mask, valwin );
....

`XCB_EVENT_MASK_EXPOSURE` 是在 `"xproto.h"` 头文件的 `xcb_event_mask_t` 枚举中定义的常量。
如果我们想注册一系列事件类型，我们可以将它们用或逻辑连接起来。就像下面这样：
[source,c]
....
mask = XCB_CW_EVENT_MASK;
valwin[0] = XCB_EVENT_MASK_EXPOSURE | XCB_EVENT_MASK_BUTTON_PRESS;
win = xcb_generate_id (connection);
xcb_create_window (connection, depth, window, root->root,
                    0, 0, 150, 150, 10,
                    XCB_WINDOW_CLASS_INPUT_OUTPUT, root->root_visual,
                    mask, valwin );
....

这将注册Expose事件以及在创建的窗口内按下鼠标按钮。 您应注意，掩码可能代表几种事件子类型。

mask值是一个xcb_cw_t类型的枚举值：
[source,c]
....
typedef enum {
    XCB_CW_BACK_PIXMAP       = 1L<<0,
    XCB_CW_BACK_PIXEL        = 1L<<1,
    XCB_CW_BORDER_PIXMAP     = 1L<<2,
    XCB_CW_BORDER_PIXEL      = 1L<<3,
    XCB_CW_BIT_GRAVITY       = 1L<<4,
    XCB_CW_WIN_GRAVITY       = 1L<<5,
    XCB_CW_BACKING_STORE     = 1L<<6,
    XCB_CW_BACKING_PLANES    = 1L<<7,
    XCB_CW_BACKING_PIXEL     = 1L<<8,
    XCB_CW_OVERRIDE_REDIRECT = 1L<<9,
    XCB_CW_SAVE_UNDER        = 1L<<10,
    XCB_CW_EVENT_MASK        = 1L<<11,
    XCB_CW_DONT_PROPAGATE    = 1L<<12,
    XCB_CW_COLORMAP          = 1L<<13,
    XCB_CW_CURSOR            = 1L<<14
} xcb_cw_t;
....

NOTE: 设置valwin参数的值时，我们必须小心，因为它们必须遵循xcb_cw_t枚举的顺序。

下面举一个例子说明:
[source,c]
....
mask = XCB_CW_EVENT_MASK | XCB_CW_BACK_PIXMAP;
valwin[0] = XCB_NONE;                                               /* for XCB_CW_BACK_PIXMAP (whose value is 1)     */
valwin[1] = XCB_EVENT_MASK_EXPOSURE | XCB_EVENT_MASK_BUTTON_PRESS;  /* for XCB_CW_EVENT_MASK, whose value (2048)     */
                                                                    /* is greater than the one of XCB_CW_BACK_PIXMAP */
....

如果已经创建了窗口，则可以使用 `xcb_change_window_attributes()` 函数来设置窗口将接收的事件。
我们将在配置窗口小节展示这个函数的原型。
例如，以下代码将窗口配置为接收Expose和ButtonPress事件：
[source,c]
....
const static uint32_t values[] = { XCB_EVENT_MASK_EXPOSURE | XCB_EVENT_MASK_BUTTON_PRESS };

xcb_change_window_attributes (connection, window, XCB_CW_EVENT_MASK, values);
....

NOTE: 程序员经常会出现这样的疏忽，添加了代码来处理新的事件类型，但在创建窗口时忘记为这些事件添加掩码。
这导致程序员进行了数小时的调试，想知道“为什么我的程序没有注意到我释放了按钮？”，最终却发现他们注册了按钮按下事件，但没有注册按钮释放事件。

=== 接收事件：编写事件循环
在注册了我们感兴趣的事件类型之后，我们需要进入一个循环，在这个循环中接收事件并对其进行处理的。
我们有两种接收事件的方式：一种阻塞和一种非阻塞：

阻塞方式:
[source,c]
....
xcb_generic_event_t *xcb_wait_for_event (xcb_connection_t *c);
....
...直到事件在X服务器中排队，然后将其从队列中出队，然后将其作为新分配的结构返回（这个需要你责任释放）。
如果在事件中发生错误，则返回NULL。

非阻塞方式:
[source,c]
....
xcb_generic_event_t *xcb_poll_for_event (xcb_connection_t *c);
....
...立即从队列中退出，并返回一个事件，但是如果在这个函数被调用的时刻没有事件可以获取到，将会返回NULL。
如果发生了一个错误，error参数将会被设置成对应错误状态。

下面演示如何使用 `xcb_wait_for_event` :
[source,c]
....
xcb_generic_event_t *event;

while ( (event = xcb_wait_for_event (connection)) ) {
    switch (event->response_type & ~0x80) {
    case XCB_EXPOSE: {
        xcb_expose_event_t *expose = (xcb_expose_event_t *)event;
        /* ...do stuff */
        break;
    }
    case XCB_BUTTON_PRESS: {
        xcb_button_press_event_t *press = (xcb_button_press_event_t *)event;
        /* ...do stuff */
        break;
    }
    default:
        /* Unknown event type, ignore it */
        break;
    }

    free (event);
}
....

在Xlib中非阻塞的处理看起来是这样的：
[source,c]
....
while (XPending (display)) {
    XEvent event;
    XNextEvent(display, &event);
    /* ...handle the event */
}
....

在XCB中同等的逻辑看起来是这样的:
[source,c]
....
xcb_generic_event_t *event;

while ( (event = xcb_poll_for_event (connection, 0)) ) {
    /* ...handle the event */
}
....

基本上，事件的管理方式与xcb_wait_for_event相同。
显然，无休止的事件处理循环将需要为用户提供某种终止程序的方式。
我们将很快看到，这通常是通过处理特殊的“退出”事件来完成的。

Xlib/XCB比较:

- XNextEvent () => xcb_wait_for_event ()
- XPending () , XCheckMaskEvent () => xcb_poll_for_event ()

=== 暴露事件
暴露事件是应用程序可能会收到的最基本（也是使用最多的）事件之一。 在以下几种情况之一中，它将被发送给我们：

- 覆盖我们窗口一部分的另一个窗口已经移开，暴露了我们窗口的一部分（或全部）。
- 我们的窗口上升到其他窗口的上面。
- 我们的窗口第一次加载。
- 我们的窗口进行了取消图标化（“图标化”窗口是将其最小化或将其发送到托盘，使其完全不显示）

请注意此处的隐含假设：我们的窗口的内容在被其他窗口遮盖（覆盖）时会丢失。X服务器不保存该内容的原因是为了节省内存。
毕竟，在某些时间里，显示器上的窗口数量可能非常大，因此存储所有窗口的内容可能需要大量内存。
(实际上，有一种方法可以告诉X服务器在特殊情况下存储窗口的内容，我们将在后面看到)

暴露事件的定义：
[source,c]
....
typedef struct {
    uint8_t      response_type; /* The type of the event, here it is XCB_EXPOSE */
    uint8_t      pad0;
    uint16_t     sequence;
    xcb_window_t window;        /* The Id of the window that receives the event (in case */
                                /* our application registered for events on several windows */
    uint16_t     x;             /* The x coordinate of the top-left part of the window that needs to be redrawn */
    uint16_t     y;             /* The y coordinate of the top-left part of the window that needs to be redrawn */
    uint16_t     width;         /* The width of the part of the window that needs to be redrawn */
    uint16_t     height;        /* The height of the part of the window that needs to be redrawn */
    uint16_t     count;
} xcb_expose_event_t;
....

=== 获取用户输入
传统上，用户输入来自两个来源：鼠标和键盘。
存在各种事件类型来通知我们用户进行了输入（按下键盘上的键，释放键盘上的键，鼠标在窗口上移动，鼠标进入（或离开）窗口等等）。

==== 鼠标按键按下和释放事件
我们要处理的第一个事件类型是窗口中的鼠标按下（或释放按钮）事件。为了注册到这样的事件类型，我们在创建窗口时应添加以下一个（或多个）掩码：
[source,c]
....
XCB_EVENT_MASK_BUTTON_PRESS     //notify us of any button that was pressed in one of our windows.
XCB_EVENT_MASK_BUTTON_RELEASE   //notify us of any button that was released in one of our windows.
....

两种事件都以相同的结构表示，但是出于自我说明的目的，它具有两个名称：
[source,c]
....
typedef struct {
    uint8_t         response_type; /* The type of the event, here it is xcb_button_press_event_t or xcb_button_release_event_t */
    xcb_button_t    detail;
    uint16_t        sequence;
    xcb_timestamp_t time;          /* Time, in milliseconds the event took place in */
    xcb_window_t    root;
    xcb_window_t    event;
    xcb_window_t    child;
    int16_t         root_x;
    int16_t         root_y;
    int16_t         event_x;       /* The x coordinate where the mouse has been pressed in the window */
    int16_t         event_y;       /* The y coordinate where the mouse has been pressed in the window */
    uint16_t        state;         /* A mask of the buttons (or keys) during the event */
    uint8_t         same_screen;
} xcb_button_press_event_t;

typedef xcb_button_press_event_t xcb_button_release_event_t;
....

time字段可用于计算应用程序的“双击”情况（例如，如果鼠标按钮在短于给定时间的时间内两次单击，则假定这是双击）。

state字段是事件期间按下的按钮的掩码。它是以下任意一项的按位“或”（来自xcbbuttonmaskt和xcbmodmaskt枚举）：
[source,c]
....
XCB_BUTTON_MASK_1
XCB_BUTTON_MASK_2
XCB_BUTTON_MASK_3
XCB_BUTTON_MASK_4
XCB_BUTTON_MASK_5
XCB_MOD_MASK_SHIFT
XCB_MOD_MASK_LOCK
XCB_MOD_MASK_CONTROL
XCB_MOD_MASK_1
XCB_MOD_MASK_2
XCB_MOD_MASK_3
XCB_MOD_MASK_4
XCB_MOD_MASK_5
....

它们的意思不言自明，前5个是指被按下的鼠标按钮，其余的是指被按下的各种“特殊键”（Mod mask 1通常是“ Alt”键或“ Meta” 键）。

TODO: 问题: 使用各种按钮单击时，状态似乎没有改变。

==== 鼠标移动事件
与鼠标按钮的按下和释放事件类似，我们也可以收到各种鼠标移动事件的通知。
我们可以分为两类情况。
一种是在没有按下任何按钮的情况下鼠标指针移动，第二种是在按下一个（或多个）按钮时的鼠标指针移动（有时称为“鼠标拖动操作”，或简称为“拖动”）。在创建窗口期间，可以添加以下事件掩码来注册这些事件：
[source,c]
....
XCB_EVENT_MASK_POINTER_MOTION   // motion with no mouse button held
XCB_EVENT_MASK_BUTTON_MOTION    // motion with one or more mouse buttons held
XCB_EVENT_MASK_BUTTON_1_MOTION  // motion while only 1st mouse button is held
XCB_EVENT_MASK_BUTTON_2_MOTION  // and so on...
XCB_EVENT_MASK_BUTTON_3_MOTION
XCB_EVENT_MASK_BUTTON_4_MOTION
XCB_EVENT_MASK_BUTTON_5_MOTION
....

这些都会生成此类事件:
[source,c]
....
typedef struct {
    uint8_t         response_type; /* The type of the event */
    uint8_t         detail;
    uint16_t        sequence;
    xcb_timestamp_t time;          /* Time, in milliseconds the event took place in */
    xcb_window_t    root;
    xcb_window_t    event;
    xcb_window_t    child;
    int16_t         root_x;
    int16_t         root_y;
    int16_t         event_x;       /* The x coordinate of the mouse when the  event was generated */
    int16_t         event_y;       /* The y coordinate of the mouse when the  event was generated */
    uint16_t        state;         /* A mask of the buttons (or keys) during the event */
    uint8_t         same_screen;
} xcb_motion_notify_event_t;
....

==== 鼠标指针进入和离开事件
应用程序可能会感兴趣的另一种事件是鼠标指针进入程序控制的窗口，或离开该窗口。 
一些程序使用这些事件向用户显示该应用程序现在处于焦点。 
为了注册这种事件类型，我们在创建窗口时应添加以下一个（或多个）掩码：

[source,c]
....
XCB_EVENT_MASK_ENTER_WINDOW     // notify us when the mouse pointer enters any of our controlled windows.
XCB_EVENT_MASK_LEAVE_WINDOW     // notify us when the mouse pointer leaves any of our controlled windows. 
....

事件循环中要检查的结构对于这两个事件是相同的，如下所示：
[source,c]
....
typedef struct {
    uint8_t         response_type; /* The type of the event */
    uint8_t         detail;
    uint16_t        sequence;
    xcb_timestamp_t time;          /* Time, in milliseconds the event took place in */
    xcb_window_t    root;
    xcb_window_t    event;
    xcb_window_t    child;
    int16_t         root_x;
    int16_t         root_y;
    int16_t         event_x;       /* The x coordinate of the mouse when the  event was generated */
    int16_t         event_y;       /* The y coordinate of the mouse when the  event was generated */
    uint16_t        state;         /* A mask of the buttons (or keys) during the event */
    uint8_t         mode;          /* The number of mouse button that was clicked */
    uint8_t         same_screen_focus;
} xcb_enter_notify_event_t;

typedef xcb_enter_notify_event_t xcb_leave_notify_event_t;
....

==== 键盘按键聚焦
屏幕上可能有许多窗口，但只有一个键盘与之相连。 X服务器如何知道给定的键盘输入应该向哪个窗口发送？ 这是使用键盘聚焦完成的。 在给定的时间，屏幕上只有一个窗口可以使键盘聚焦。 有一个XCB功能，允许程序将键盘焦点设置到给定的窗口。 用户通常可以使用窗口管理器设置键盘焦点（通常通过单击所需窗口的标题栏）。 一旦我们的窗口具有键盘焦点，每次按键或释放按键都会将一个事件发送到我们的程序（如果它已注册了这些事件类型...）。

==== 键盘按键按下和释放事件
If a window controlled by our program currently holds the keyboard focus, it can receive key press and key release events. So, we should add one (or more) of the following masks when we create our window:
[source,c]
....
XCB_EVENT_MASK_KEY_PRESS     // key was pressed while any of our controlled windows had the keyboard focus
XCB_EVENT_MASK_KEY_RELEASE   // key was released while any of our controlled windows had the keyboard focus
....
These generate events of the same type, which goes by two names:
[source,c]
....
typedef struct {
    uint8_t         response_type; /* The type of the event */
    xcb_keycode_t   detail;        /* the physical key on the keyboard */
    uint16_t        sequence;
    xcb_timestamp_t time;          /* Time, in milliseconds the event took place in */
    xcb_window_t    root;
    xcb_window_t    event;
    xcb_window_t    child;
    int16_t         root_x;
    int16_t         root_y;
    int16_t         event_x;
    int16_t         event_y;
    uint16_t        state;
    uint8_t         same_screen;
} xcb_key_press_event_t;

typedef xcb_key_press_event_t  xcb_key_release_event_t;
....

TODO: 讨论从按键代码获取ASCII码。

=== X事件: 一个完整的示例
作为演示处理事件，我们写了一个程序，该程序创建一个窗口，进入事件循环并检查上述所有事件，并在终端上编写事件的相关特征。 使用此代码，应该很容易添加绘图操作，就像上面已经描述的那样。
[source,c]
....
#include <stdlib.h>
#include <stdio.h>
#include <inttypes.h>

#include <xcb/xcb.h>

/* print names of modifiers present in mask */
void
print_modifiers (uint32_t mask)
{
    const char *MODIFIERS[] = {
            "Shift", "Lock", "Ctrl", "Alt",
            "Mod2", "Mod3", "Mod4", "Mod5",
            "Button1", "Button2", "Button3", "Button4", "Button5"
    };

    printf ("Modifier mask: ");
    for (const char **modifier = MODIFIERS ; mask; mask >>= 1, ++modifier) {
        if (mask & 1) {
            printf (*modifier);
        }
    }
    printf ("\n");
}

int
main ()
{
    /* Open the connection to the X server */
    xcb_connection_t *connection = xcb_connect (NULL, NULL);

    /* Get the first screen */
    xcb_screen_t *screen = xcb_setup_roots_iterator (xcb_get_setup (connection)).data;


    /* Create the window */
    xcb_window_t window    = xcb_generate_id (connection);

    uint32_t     mask      = XCB_CW_BACK_PIXEL | XCB_CW_EVENT_MASK;
    uint32_t     values[2] = {screen->white_pixel,
                                XCB_EVENT_MASK_EXPOSURE       | XCB_EVENT_MASK_BUTTON_PRESS   |
                                XCB_EVENT_MASK_BUTTON_RELEASE | XCB_EVENT_MASK_POINTER_MOTION |
                                XCB_EVENT_MASK_ENTER_WINDOW   | XCB_EVENT_MASK_LEAVE_WINDOW   |
                                XCB_EVENT_MASK_KEY_PRESS      | XCB_EVENT_MASK_KEY_RELEASE };

    xcb_create_window (connection,    
                        0,                             /* depth               */
                        window,                        
                        screen->root,                  /* parent window       */
                        0, 0,                          /* x, y                */
                        150, 150,                      /* width, height       */
                        10,                            /* border_width        */
                        XCB_WINDOW_CLASS_INPUT_OUTPUT, /* class               */
                        screen->root_visual,           /* visual              */
                        mask, values );                /* masks */

    /* Map the window on the screen */
    xcb_map_window (connection, window);

    xcb_flush (connection);

    xcb_generic_event_t *event;
    while ( (event = xcb_wait_for_event (connection)) ) {
        switch (event->response_type & ~0x80) {
        case XCB_EXPOSE: {
            xcb_expose_event_t *expose = (xcb_expose_event_t *)event;

            printf ("Window %"PRIu32" exposed. Region to be redrawn at location (%"PRIu16",%"PRIu16"), with dimension (%"PRIu16",%"PRIu16")\n",
                    expose->window, expose->x, expose->y, expose->width, expose->height );
            break;
        }
        case XCB_BUTTON_PRESS: {
            xcb_button_press_event_t *bp = (xcb_button_press_event_t *)event;
            print_modifiers (bp->state);

            switch (bp->detail) {
            case 4:
                printf ("Wheel Button up in window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                        bp->event, bp->event_x, bp->event_y );
                break;
            case 5:
                printf ("Wheel Button down in window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                        bp->event, bp->event_x, bp->event_y );
                break;
            default:
                printf ("Button %"PRIu8" pressed in window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                        bp->detail, bp->event, bp->event_x, bp->event_y );
                break;
            }
            break;
        }
        case XCB_BUTTON_RELEASE: {
            xcb_button_release_event_t *br = (xcb_button_release_event_t *)event;
            print_modifiers(br->state);

            printf ("Button %"PRIu8" released in window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                    br->detail, br->event, br->event_x, br->event_y );
            break;
        }
        case XCB_MOTION_NOTIFY: {
            xcb_motion_notify_event_t *motion = (xcb_motion_notify_event_t *)event;

            printf ("Mouse moved in window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                    motion->event, motion->event_x, motion->event_y );
            break;
        }
        case XCB_ENTER_NOTIFY: {
            xcb_enter_notify_event_t *enter = (xcb_enter_notify_event_t *)event;

            printf ("Mouse entered window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                    enter->event, enter->event_x, enter->event_y );
            break;
        }
        case XCB_LEAVE_NOTIFY: {
            xcb_leave_notify_event_t *leave = (xcb_leave_notify_event_t *)event;

            printf ("Mouse left window %"PRIu32", at coordinates (%"PRIi16",%"PRIi16")\n",
                    leave->event, leave->event_x, leave->event_y );
            break;
        }
        case XCB_KEY_PRESS: {
            xcb_key_press_event_t *kp = (xcb_key_press_event_t *)event;
            print_modifiers(kp->state);

            printf ("Key pressed in window %"PRIu32"\n",
                    kp->event);
            break;
        }
        case XCB_KEY_RELEASE: {
            xcb_key_release_event_t *kr = (xcb_key_release_event_t *)event;
            print_modifiers(kr->state);

            printf ("Key released in window %"PRIu32"\n",
                    kr->event);
            break;
        }
        default:
            /* Unknown event type, ignore it */
            printf ("Unknown event: %"PRIu8"\n",
                    event->response_type);
            break;
        }

        free (event);
    }

    return 0;
}
....
Links: XcbPorting link:../tutorial.adoc[tutorial]

Last edited Tue 03 Dec 2013 05:20:34 AM UTC