= 文本和字体处理
:toc:
:toc-title: 目录
:numbered:

除了在窗口上绘制图形外，我们通常还希望绘制文本。 文本字符串具有两个主要属性：要绘制的字符和绘制它们的字体。
为了绘制文本，我们需要首先请求X服务器加载字体。 然后，将字体分配给图形上下文，最后，使用图形上下文在窗口中绘制文本。

=== 字体结构体
为了支持灵活的字体，定义了一种字体类型，猜测一下，它应该是一个ID：
[source,c]
....
typedef uint32_t xcb_font_t;
....
字体ID会传递给处理字体选择和文本绘制的多个函数。我们要求X服务器使用以下函数将Id赋予给我们的字体：
[source,c]
....
xcb_font_t xcb_generate_id (xcb_connection_t *c);
....

=== 打开一个字体
我们使用下面的这个函数来打开字体：
[source,c]
....
xcb_void_cookie_t xcb_open_font (xcb_connection_t *c,
                                    xcb_font_t        fid,
                                    uint16_t          name_len,
                                    const char       *name);
....

`fid` 参数是由 `xcb_generate_id()` 定义的字体ID（请参见上面）。`name` 参数是您要打开的字体的名称。 在终端中使用命令 `xlsfonts` 可以了解计算机上可用的字体。参数 `name_len` 是字体名称的长度（由 `strlen()` 给出）。

=== 将字体分配给图形上下文
打开字体后，您必须创建一个图形上下文，其中包含有关在可绘制对象中绘制文本时使用的前景色和背景色的信息。 这是一个图形上下文的示例，它使我们能够绘制带有黑色前景和白色背景的打开的字体：

[source,c]
....
/*
* c is the connection
* screen is the screen where the window is displayed
* window is the window in which we will draw the text
* font is the opened font
*/

uint32_t             value_list[3];
xcb_gcontext_t       gc;
uint32_t             mask;

gc = xcb_generate_id (c);
mask = XCB_GC_FOREGROUND | XCB_GC_BACKGROUND | XCB_GC_FONT;
value_list[0] = screen->black_pixel;
value_list[1] = screen->white_pixel;
value_list[2] = font;
xcb_create_gc (c, gc, window, mask, value_list);

/* The font is not needed anymore, so we close it */
xcb_close_font (c, font);
....

=== 在可绘制图形中绘制文本
为了在可绘制对象中绘制文本，我们需要使用下面的这个函数：
[source,c]
....
    xcb_void_cookie_t xcb_image_text_8 (xcb_connection_t *c,
                                        uint8_t           string_len,
                                        xcb_drawable_t    drawable,
                                        xcb_gcontext_t    gc,
                                        int16_t           x,
                                        int16_t           y,
                                        const char       *string);
....

字符串参数是要绘制的文本。绘制的位置由参数x和y给出。文本的基线恰好是参数y。

=== 完整的例子
本示例在窗口底部的10个像素处（相对于基线）绘制文本。按Esc键退出程序。
[source,c]
....
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <inttypes.h>

#include <xcb/xcb.h>

#define WIDTH 300
#define HEIGHT 100


static xcb_gc_t getFontGC (xcb_connection_t *c,
                                xcb_screen_t     *screen,
                                xcb_window_t      window,
                                const char       *font_name );


static void drawText (xcb_connection_t *c,
                        xcb_screen_t     *screen,
                        xcb_window_t      window,
                        int16_t           x1,
                        int16_t           y1,
                        const char       *label );


static void
testCookie (xcb_void_cookie_t cookie,
            xcb_connection_t *connection,
            char *errMessage )
{
    xcb_generic_error_t *error = xcb_request_check (connection, cookie);
    if (error) {
        fprintf (stderr, "ERROR: %s : %"PRIu8"\n", errMessage , error->error_code);
        xcb_disconnect (connection);
        exit (-1);
    }
}

static void
drawText (xcb_connection_t  *connection,
            xcb_screen_t     *screen,
            xcb_window_t      window,
            int16_t           x1,
            int16_t           y1,
            const char       *label )
{

    /* get graphics context */
    xcb_gcontext_t gc = getFontGC (connection, screen, window, "fixed");


    /* draw the text */
    xcb_void_cookie_t textCookie = xcb_image_text_8_checked (connection,
                                                                strlen (label),
                                                                window,
                                                                gc,
                                                                x1, y1,
                                                                label );

    testCookie(textCookie, connection, "can't paste text");


    /* free the gc */
    xcb_void_cookie_t gcCookie = xcb_free_gc (connection, gc);

    testCookie(gcCookie, connection, "can't free gc");
}


static xcb_gc_t
getFontGC (xcb_connection_t  *connection,
            xcb_screen_t      *screen,
            xcb_window_t       window,
            const char        *font_name )
{
    /* get font */
    xcb_font_t font = xcb_generate_id (connection);
    xcb_void_cookie_t fontCookie = xcb_open_font_checked (connection,
                                                            font,
                                                            strlen (font_name),
                                                            font_name );

    testCookie(fontCookie, connection, "can't open font");


    /* create graphics context */
    xcb_gcontext_t  gc            = xcb_generate_id (connection);
    uint32_t        mask          = XCB_GC_FOREGROUND | XCB_GC_BACKGROUND | XCB_GC_FONT;
    uint32_t        value_list[3] = { screen->black_pixel,
                                        screen->white_pixel,
                                        font };

    xcb_void_cookie_t gcCookie = xcb_create_gc_checked (connection,
                                                        gc,
                                                        window,
                                                        mask,
                                                        value_list );

    testCookie(gcCookie, connection, "can't create gc");


    /* close font */
    fontCookie = xcb_close_font_checked (connection, font);

    testCookie(fontCookie, connection, "can't close font");

    return gc;
}


int
main ()
{
    /* get the connection */
    int screenNum;
    xcb_connection_t *connection = xcb_connect (NULL, &screenNum);
    if (!connection) {
        fprintf (stderr, "ERROR: can't connect to an X server\n");
        return -1;
    }


    /* get the current screen */
    xcb_screen_iterator_t iter = xcb_setup_roots_iterator (xcb_get_setup (connection));

    // we want the screen at index screenNum of the iterator
    for (int i = 0; i < screenNum; ++i) {
        xcb_screen_next (&iter);
    }

    xcb_screen_t *screen = iter.data;

    if (!screen) {
        fprintf (stderr, "ERROR: can't get the current screen\n");
        xcb_disconnect (connection);
        return -1;
    }


    /* create the window */
    xcb_window_t window = xcb_generate_id (connection);

    uint32_t mask = XCB_CW_BACK_PIXEL | XCB_CW_EVENT_MASK;
    uint32_t values[2];
    values[0] = screen->white_pixel;
    values[1] = XCB_EVENT_MASK_KEY_RELEASE |
                XCB_EVENT_MASK_BUTTON_PRESS |
                XCB_EVENT_MASK_EXPOSURE |
                XCB_EVENT_MASK_POINTER_MOTION;

    xcb_void_cookie_t windowCookie = xcb_create_window_checked (connection,
                                                                screen->root_depth,
                                                                window, screen->root,
                                                                20, 200, 
                                                                WIDTH, HEIGHT,
                                                                0, XCB_WINDOW_CLASS_INPUT_OUTPUT,
                                                                screen->root_visual,
                                                                mask, values);

    testCookie(windowCookie, connection, "can't create window");

    xcb_void_cookie_t mapCookie = xcb_map_window_checked (connection, window);

    testCookie(mapCookie, connection, "can't map window");

    xcb_flush(connection);  // make sure window is drawn


    /* event loop */
    xcb_generic_event_t  *event;
    while (1) { ;
        if ( (event = xcb_poll_for_event(connection)) ) {
            switch (event->response_type & ~0x80) {
                case XCB_EXPOSE: {
                    drawText (connection, 
                                screen,
                                window,
                                10, HEIGHT - 10,
                                "Press ESC key to exit..." );
                    break;
                }
                case XCB_KEY_RELEASE: {
                    xcb_key_release_event_t *kr = (xcb_key_release_event_t *)event;

                    switch (kr->detail) {
                        /* ESC */
                        case 9: {
                            free (event);
                            xcb_disconnect (connection);
                            return 0;
                        }
                    }
                    free (event);
                }
            }
        }
    }
    return 0;
}
....

Links: link:../tutorial.adoc[tutorial]

Last edited Tue 03 Dec 2013 05:20:34 AM UTC