= Xcb
:toc:
:numbered:

== 介绍
X协议C语言绑定（XCB）替代了Xlib，具有占用空间小，低延迟，直接访问协议，改进的线程支持和可扩展性的特点。

== 新闻
2020年2月: 发布了 https://lists.x.org/archives/xorg-announce/2020-February/003038.html[xcb-proto 1.14] 和 https://lists.x.org/archives/xorg-announce/2020-February/003039.html[libxcb 1.14] 。除了修复Bug外，这还带来了check> = 0.13的兼容性，并添加了xcb_total_read()和xcb_total_write() API。

2018年3月: 发布了 https://lists.freedesktop.org/archives/xcb/2018-March/011090.html[xcb-proto 1.13] 和 https://lists.freedesktop.org/archives/xcb/2018-March/011091.html[libxcb 1.13] 。除了修复Bug外，这还可以启用某些协议的已完成的新版本。

2016年5月: 发布了 https://lists.x.org/archives/xorg-announce/2016-May/002693.html[xcb-proto 1.12] 和 https://lists.x.org/archives/xorg-announce/2016-May/002694.html[libxcb 1.12] 。

2015年9月: 发布了 http://lists.x.org/archives/xorg-announce/2015-September/002633.html[libxcb 1.11.1] 。 这修复了一些与线程相关的问题，并添加了某些API的64位版本。

2014年8月: 发布了 http://lists.x.org/archives/xorg-announce/2014-August/002468.html[xcb-proto 1.11] 和 http://lists.x.org/archives/xorg-announce/2014-August/002469.html[libxcb 1.11] 。这又是一个修复大量bug的版本。

2013年12月: 发布了 http://lists.x.org/archives/xorg-announce/2013-December/002382.html[xcb-proto 1.10] 和 http://lists.x.org/archives/xorg-announce/2013-December/002383.html[libxcb 1.10] 。这次主要解决了libxcb 1.9.2中引入的一些API和ABI问题。 有关更多详细信息，请参见链接的公告。

2013年5月: 发布了 http://lists.x.org/archives/xorg-announce/2013-May/002230.html[libxcb 1.9.1] 。 使python代码能在Python 3下正常工作, 同时修复了read_packet()函数中的整型溢出的问题 (http://www.x.org/wiki/Development/Security/Advisory-2013-05-23/[CVE-2013-2064])

2012年10月: 新的XCB包版本已经发布, 包括XCB API自动生成的手册页 - 有关每个更改的详细信息，请参见链接的公告：

- http://lists.freedesktop.org/archives/xcb/2012-October/007892.html[xcb-proto 1.8]
- http://lists.freedesktop.org/archives/xcb/2012-October/007893.html[libxcb 1.9]

== 下载
您可以从 http://xcb.freedesktop.org/dist[此处]获得XCB的发行版本。

遵循 https://xcb.freedesktop.org/DevelopersGuide/[开发人员指南]中的说明进行构建，除了可以使用发行版的依赖项，并且不需要git，automake，autoconf或libtool。

== 开发
- 假如你想从事XCB开发工作, 请阅读 https://xcb.freedesktop.org/DevelopersGuide/[开发人员指南]。
- 邮件列表: XCB和Xlib/XCB的交流是通过 http://lists.freedesktop.org/mailman/listinfo/xcb[XCB邮件列表]完成的。
- IRC: XCB开发人员也参加 https://xcb.freedesktop.org/IRC/[IRC], 并且会不定期举行 https://xcb.freedesktop.org/Meetings/[会议]。
- 当然，现在仍然还有很多 link:xcb/todo.adoc[待完成]内容。

== 文档
- https://xcb.freedesktop.org/XcbApi/[XCB API]已经文档化了. 此处还有一个 link:xcb/tutorial.adoc[教程]和一些零散的 link:xcb/xcbnote.adoc[笔记]。
- 如果想进行上层应用的开发，可以使用 https://xcb.freedesktop.org/XcbUtil/[xcb-util].
- XCB是构建在一个由XML描述的X核心协议以及被称为XML/XCB的通用拓展协议之上的。该协议可以以其他有趣的方式使用。X窗口协议文档同样可以在 http://www.x.org/releases/X11R7.7/doc/index.html#protocol[X.org的官网]上获取到。并且可以与XCB文档结合使用，因为XCB方法在很大程度上反映了协议。
- 为了帮助移植应用程序，您可以配置Xlib以将XCB用于传输层. 我们把这称之为 https://xcb.freedesktop.org/XlibXcb/[Xlib/XCB].
- 这是一份自动生成的 http://xcb.freedesktop.org/manual/modules.html[XCB协议绑定文档].
- XCB的Windows（32位）适配代码将很快合并到主代码库中。 你可以从 https://xcb.freedesktop.org/win32port/[此处]获取更多内容.

== 杂项
- https://xcb.freedesktop.org/KittyLogo/[XCB logo]
- XCB项目拥有很长的 https://xcb.freedesktop.org/History/[历史], 在这段历史里产生了许许多多的学术 https://xcb.freedesktop.org/Publications/[期刊]。各种项目都已经 https://xcb.freedesktop.org/adoption/[适配]了XCB。

链接: https://xcb.freedesktop.org/XCBDevelopmentPlan/[XCBDevelopmentPlan] link:xcb/todo.adoc[XCBToDo] https://xcb.freedesktop.org/XcbApi/[XcbApi] https://xcb.freedesktop.org/XmlXcb/[XmlXcb] link:xcb/usingxcb.adoc[usingxcb]

Last edited Mon Mar 2 22:57:26 2020