= Xcb

== 介绍
The X protocol C-language Binding (XCB) is a replacement for Xlib link:xcb/features.adoc[featuring] a small footprint, latency hiding, direct access to the protocol, improved threading support, and extensibility.

== 新闻
February 2020: https://lists.x.org/archives/xorg-announce/2020-February/003038.html[xcb-proto 1.14] and https://lists.x.org/archives/xorg-announce/2020-February/003039.html[libxcb 1.14] were released. In addition to fixing bugs, this brings compatibility with check >= 0.13 and adds xcb_total_read() and xcb_total_written() APIs.

March 2018: https://lists.freedesktop.org/archives/xcb/2018-March/011090.html[xcb-proto 1.13] and https://lists.freedesktop.org/archives/xcb/2018-March/011091.html[libxcb 1.13] were released. In addition to fixing bugs, this enables new and completed versions of some protocols.

May 2016: https://lists.x.org/archives/xorg-announce/2016-May/002693.html[xcb-proto 1.12] and https://lists.x.org/archives/xorg-announce/2016-May/002694.html[libxcb 1.12] were released.

September 2015: http://lists.x.org/archives/xorg-announce/2015-September/002633.html[libxcb 1.11.1] was released. This fixes some thread-related issues and adds 64-bit versions of some APIs.

August 2014: http://lists.x.org/archives/xorg-announce/2014-August/002468.html[xcb-proto 1.11] and http://lists.x.org/archives/xorg-announce/2014-August/002469.html[libxcb 1.11] were released. This is again mostly a bug-fix release.

December 2013: http://lists.x.org/archives/xorg-announce/2013-December/002382.html[xcb-proto 1.10] and http://lists.x.org/archives/xorg-announce/2013-December/002383.html[libxcb 1.10] were released, this time mainly fixing some API and ABI issues introduced with libxcb 1.9.2. See the linked announcements for more details.

May 2013: http://lists.x.org/archives/xorg-announce/2013-May/002230.html[libxcb 1.9.1] was released, fixing the python code to work with Python 3, and fixing an integer overflow in the read_packet() function (http://www.x.org/wiki/Development/Security/Advisory-2013-05-23/[CVE-2013-2064])

October 2012: New releases of the XCB packages have been published, including autogenerated man pages for XCB API's - see the linked announcements for full details of what's changed in each one:

- http://lists.freedesktop.org/archives/xcb/2012-October/007892.html[xcb-proto 1.8]
- http://lists.freedesktop.org/archives/xcb/2012-October/007893.html[libxcb 1.9]

== 下载
You can obtain released versions of XCB from http://xcb.freedesktop.org/dist.
Follow the instructions from the https://xcb.freedesktop.org/DevelopersGuide/[developer's guide] to build, except that you can use released versions of the dependencies, and you don't need git, automake, autoconf, or libtool.

== 开发
- If you wish to work on XCB, please read the https://xcb.freedesktop.org/DevelopersGuide/[developer's guide].
- Mailing list: Discussion of XCB and Xlib/XCB is through the http://lists.freedesktop.org/mailman/listinfo/xcb[XCB mailing list].
- IRC: XCB developers also hang out on https://xcb.freedesktop.org/IRC/[IRC], and have occasional https://xcb.freedesktop.org/Meetings/[meetings].
- Of course, there's still a lot link:xcb/todo.adoc[to do] .

== 文档
- The https://xcb.freedesktop.org/XcbApi/[XCB API] is documented. There is also a link:xcb/tutorial.adoc[tutorial] and some random link:xcb/xcbnote.adoc[notes].
- People wanting to implement higher level applications can use https://xcb.freedesktop.org/XcbUtil/[xcb-util].
- XCB is built atop an XML description of the X core protocol and common extension protocols called https://xcb.freedesktop.org/XmlXcb/[XML/XCB]. This protocol can be used in other interesting ways. Documentation of the X Window System protocol is also available at http://www.x.org/releases/X11R7.7/doc/index.html#protocol[X.org's website], and can be used in combination with XCB documentation as XCB functions largely reflect the protocol.
- To aid in porting applications, you can configure Xlib to use XCB for the transport layer. We call this https://xcb.freedesktop.org/XlibXcb/[Xlib/XCB].
- There is automatically-generated http://xcb.freedesktop.org/manual/modules.html[documentation for the XCB protocol bindings].
- The Windows (32 bit) port of XCB will be merged into the main code base soon. You can read more on that https://xcb.freedesktop.org/win32port/[here].

== 杂项
- https://xcb.freedesktop.org/KittyLogo/[The XCB logo]
- The XCB project has a long https://xcb.freedesktop.org/History/[history], during which it has produced many academic https://xcb.freedesktop.org/Publications/[publications]. Various projects have https://xcb.freedesktop.org/adoption/[adopted] XCB.

链接: https://xcb.freedesktop.org/XCBDevelopmentPlan/[XCBDevelopmentPlan] link:xcb/todo.adoc[XCBToDo] https://xcb.freedesktop.org/XcbApi/[XcbApi] https://xcb.freedesktop.org/XmlXcb/[XmlXcb] link:xcb/usingxcb.adoc[usingxcb]

Last edited Mon Mar 2 22:57:26 2020